namespace sistema_contabilidad.Formularios
{
    partial class FrmLibroDiario
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            panelEncabezado = new Panel();
            lblTitulo = new Label();
            grpDatos = new GroupBox();
            lblNumeroCap = new Label();
            lblNumero = new Label();
            lblFechaCap = new Label();
            dtpFecha = new DateTimePicker();
            lblConceptoCap = new Label();
            txtConcepto = new TextBox();
            grpAgregar = new GroupBox();
            lblCuenta = new Label();
            cboCuenta = new ComboBox();
            lblConceptoLinea = new Label();
            txtConceptoLinea = new TextBox();
            lblDebe = new Label();
            txtDebe = new TextBox();
            lblHaber = new Label();
            txtHaber = new TextBox();
            btnAgregarLinea = new Button();
            btnQuitarLinea = new Button();
            btnCalcIva = new Button();
            dgvDetalle = new DataGridView();
            panelInferior = new Panel();
            lblTotDebeCap = new Label();
            lblTotDebe = new Label();
            lblTotHaberCap = new Label();
            lblTotHaber = new Label();
            lblDifCap = new Label();
            lblDiferencia = new Label();
            btnGuardar = new Button();
            btnLimpiar = new Button();
            panelEncabezado.SuspendLayout();
            grpDatos.SuspendLayout();
            grpAgregar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvDetalle).BeginInit();
            panelInferior.SuspendLayout();
            SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(33, 71, 115);
            panelEncabezado.Controls.Add(lblTitulo);
            panelEncabezado.Dock = DockStyle.Top;
            panelEncabezado.Location = new Point(0, 0);
            panelEncabezado.Name = "panelEncabezado";
            panelEncabezado.Size = new Size(940, 55);
            panelEncabezado.TabIndex = 0;
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 15F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.White;
            lblTitulo.Location = new Point(16, 12);
            lblTitulo.Name = "lblTitulo";
            lblTitulo.Size = new Size(330, 28);
            lblTitulo.TabIndex = 0;
            lblTitulo.Text = "Libro Diario - Registro de Asientos";
            grpDatos.Controls.Add(lblNumeroCap);
            grpDatos.Controls.Add(lblNumero);
            grpDatos.Controls.Add(lblFechaCap);
            grpDatos.Controls.Add(dtpFecha);
            grpDatos.Controls.Add(lblConceptoCap);
            grpDatos.Controls.Add(txtConcepto);
            grpDatos.Dock = DockStyle.Top;
            grpDatos.Location = new Point(0, 55);
            grpDatos.Name = "grpDatos";
            grpDatos.Padding = new Padding(10);
            grpDatos.Size = new Size(940, 75);
            grpDatos.TabIndex = 1;
            grpDatos.TabStop = false;
            grpDatos.Text = "Datos del asiento";
            lblNumeroCap.AutoSize = true;
            lblNumeroCap.Location = new Point(15, 33);
            lblNumeroCap.Name = "lblNumeroCap";
            lblNumeroCap.Size = new Size(78, 20);
            lblNumeroCap.TabIndex = 0;
            lblNumeroCap.Text = "Asiento N°:";
            lblNumero.AutoSize = true;
            lblNumero.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblNumero.ForeColor = Color.FromArgb(33, 71, 115);
            lblNumero.Location = new Point(99, 33);
            lblNumero.Name = "lblNumero";
            lblNumero.Size = new Size(18, 23);
            lblNumero.TabIndex = 1;
            lblNumero.Text = "1";
            lblFechaCap.AutoSize = true;
            lblFechaCap.Location = new Point(180, 33);
            lblFechaCap.Name = "lblFechaCap";
            lblFechaCap.Size = new Size(51, 20);
            lblFechaCap.TabIndex = 2;
            lblFechaCap.Text = "Fecha:";
            dtpFecha.Format = DateTimePickerFormat.Short;
            dtpFecha.Location = new Point(237, 29);
            dtpFecha.Name = "dtpFecha";
            dtpFecha.Size = new Size(140, 27);
            dtpFecha.TabIndex = 3;
            lblConceptoCap.AutoSize = true;
            lblConceptoCap.Location = new Point(420, 33);
            lblConceptoCap.Name = "lblConceptoCap";
            lblConceptoCap.Size = new Size(76, 20);
            lblConceptoCap.TabIndex = 4;
            lblConceptoCap.Text = "Concepto:";
            txtConcepto.Location = new Point(502, 29);
            txtConcepto.Name = "txtConcepto";
            txtConcepto.Size = new Size(420, 27);
            txtConcepto.TabIndex = 5;
            grpAgregar.Controls.Add(lblCuenta);
            grpAgregar.Controls.Add(cboCuenta);
            grpAgregar.Controls.Add(lblConceptoLinea);
            grpAgregar.Controls.Add(txtConceptoLinea);
            grpAgregar.Controls.Add(lblDebe);
            grpAgregar.Controls.Add(txtDebe);
            grpAgregar.Controls.Add(lblHaber);
            grpAgregar.Controls.Add(txtHaber);
            grpAgregar.Controls.Add(btnAgregarLinea);
            grpAgregar.Controls.Add(btnQuitarLinea);
            grpAgregar.Controls.Add(btnCalcIva);
            grpAgregar.Dock = DockStyle.Top;
            grpAgregar.Location = new Point(0, 130);
            grpAgregar.Name = "grpAgregar";
            grpAgregar.Padding = new Padding(10);
            grpAgregar.Size = new Size(940, 115);
            grpAgregar.TabIndex = 2;
            grpAgregar.TabStop = false;
            grpAgregar.Text = "Agregar movimiento";
            lblCuenta.AutoSize = true;
            lblCuenta.Location = new Point(15, 33);
            lblCuenta.Name = "lblCuenta";
            lblCuenta.Size = new Size(60, 20);
            lblCuenta.TabIndex = 0;
            lblCuenta.Text = "Cuenta:";
            cboCuenta.DropDownStyle = ComboBoxStyle.DropDownList;
            cboCuenta.FormattingEnabled = true;
            cboCuenta.Location = new Point(81, 29);
            cboCuenta.Name = "cboCuenta";
            cboCuenta.Size = new Size(330, 28);
            cboCuenta.TabIndex = 1;
            lblConceptoLinea.AutoSize = true;
            lblConceptoLinea.Location = new Point(430, 33);
            lblConceptoLinea.Name = "lblConceptoLinea";
            lblConceptoLinea.Size = new Size(76, 20);
            lblConceptoLinea.TabIndex = 2;
            lblConceptoLinea.Text = "Concepto:";
            txtConceptoLinea.Location = new Point(512, 29);
            txtConceptoLinea.Name = "txtConceptoLinea";
            txtConceptoLinea.Size = new Size(260, 27);
            txtConceptoLinea.TabIndex = 3;
            lblDebe.AutoSize = true;
            lblDebe.Location = new Point(15, 73);
            lblDebe.Name = "lblDebe";
            lblDebe.Size = new Size(46, 20);
            lblDebe.TabIndex = 4;
            lblDebe.Text = "Debe:";
            txtDebe.Location = new Point(81, 69);
            txtDebe.Name = "txtDebe";
            txtDebe.Size = new Size(140, 27);
            txtDebe.TabIndex = 5;
            txtDebe.Text = "0.00";
            txtDebe.TextAlign = HorizontalAlignment.Right;
            lblHaber.AutoSize = true;
            lblHaber.Location = new Point(250, 73);
            lblHaber.Name = "lblHaber";
            lblHaber.Size = new Size(51, 20);
            lblHaber.TabIndex = 6;
            lblHaber.Text = "Haber:";
            txtHaber.Location = new Point(307, 69);
            txtHaber.Name = "txtHaber";
            txtHaber.Size = new Size(140, 27);
            txtHaber.TabIndex = 7;
            txtHaber.Text = "0.00";
            txtHaber.TextAlign = HorizontalAlignment.Right;
            btnAgregarLinea.BackColor = Color.FromArgb(39, 128, 73);
            btnAgregarLinea.FlatStyle = FlatStyle.Flat;
            btnAgregarLinea.ForeColor = Color.White;
            btnAgregarLinea.Location = new Point(662, 66);
            btnAgregarLinea.Name = "btnAgregarLinea";
            btnAgregarLinea.Size = new Size(110, 32);
            btnAgregarLinea.TabIndex = 8;
            btnAgregarLinea.Text = "Agregar línea";
            btnAgregarLinea.UseVisualStyleBackColor = false;
            btnAgregarLinea.Click += btnAgregarLinea_Click;
            btnQuitarLinea.BackColor = Color.FromArgb(150, 40, 40);
            btnQuitarLinea.FlatStyle = FlatStyle.Flat;
            btnQuitarLinea.ForeColor = Color.White;
            btnQuitarLinea.Location = new Point(795, 66);
            btnQuitarLinea.Name = "btnQuitarLinea";
            btnQuitarLinea.Size = new Size(110, 32);
            btnQuitarLinea.TabIndex = 9;
            btnQuitarLinea.Text = "Quitar línea";
            btnQuitarLinea.UseVisualStyleBackColor = false;
            btnQuitarLinea.Click += btnQuitarLinea_Click;
            btnCalcIva.FlatStyle = FlatStyle.Flat;
            btnCalcIva.Location = new Point(500, 66);
            btnCalcIva.Name = "btnCalcIva";
            btnCalcIva.Size = new Size(120, 32);
            btnCalcIva.TabIndex = 10;
            btnCalcIva.Text = "Calc. IVA";
            btnCalcIva.UseVisualStyleBackColor = true;
            btnCalcIva.Click += btnCalcIva_Click;
            dgvDetalle.AllowUserToAddRows = false;
            dgvDetalle.AllowUserToDeleteRows = false;
            dgvDetalle.BackgroundColor = Color.White;
            dgvDetalle.BorderStyle = BorderStyle.None;
            dgvDetalle.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvDetalle.Dock = DockStyle.Fill;
            dgvDetalle.Location = new Point(0, 245);
            dgvDetalle.Name = "dgvDetalle";
            dgvDetalle.ReadOnly = true;
            dgvDetalle.RowHeadersVisible = false;
            dgvDetalle.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvDetalle.Size = new Size(940, 235);
            dgvDetalle.TabIndex = 3;
            panelInferior.BackColor = Color.FromArgb(238, 243, 249);
            panelInferior.Controls.Add(lblTotDebeCap);
            panelInferior.Controls.Add(lblTotDebe);
            panelInferior.Controls.Add(lblTotHaberCap);
            panelInferior.Controls.Add(lblTotHaber);
            panelInferior.Controls.Add(lblDifCap);
            panelInferior.Controls.Add(lblDiferencia);
            panelInferior.Controls.Add(btnGuardar);
            panelInferior.Controls.Add(btnLimpiar);
            panelInferior.Dock = DockStyle.Bottom;
            panelInferior.Location = new Point(0, 480);
            panelInferior.Name = "panelInferior";
            panelInferior.Size = new Size(940, 95);
            panelInferior.TabIndex = 4;
            lblTotDebeCap.AutoSize = true;
            lblTotDebeCap.Location = new Point(16, 15);
            lblTotDebeCap.Name = "lblTotDebeCap";
            lblTotDebeCap.Size = new Size(87, 20);
            lblTotDebeCap.TabIndex = 0;
            lblTotDebeCap.Text = "Total Debe:";
            lblTotDebe.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblTotDebe.Location = new Point(120, 13);
            lblTotDebe.Name = "lblTotDebe";
            lblTotDebe.Size = new Size(140, 25);
            lblTotDebe.TabIndex = 1;
            lblTotDebe.Text = "0.00";
            lblTotDebe.TextAlign = ContentAlignment.MiddleRight;
            lblTotHaberCap.AutoSize = true;
            lblTotHaberCap.Location = new Point(16, 43);
            lblTotHaberCap.Name = "lblTotHaberCap";
            lblTotHaberCap.Size = new Size(92, 20);
            lblTotHaberCap.TabIndex = 2;
            lblTotHaberCap.Text = "Total Haber:";
            lblTotHaber.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblTotHaber.Location = new Point(120, 41);
            lblTotHaber.Name = "lblTotHaber";
            lblTotHaber.Size = new Size(140, 25);
            lblTotHaber.TabIndex = 3;
            lblTotHaber.Text = "0.00";
            lblTotHaber.TextAlign = ContentAlignment.MiddleRight;
            lblDifCap.AutoSize = true;
            lblDifCap.Location = new Point(300, 15);
            lblDifCap.Name = "lblDifCap";
            lblDifCap.Size = new Size(84, 20);
            lblDifCap.TabIndex = 4;
            lblDifCap.Text = "Diferencia:";
            lblDiferencia.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblDiferencia.ForeColor = Color.FromArgb(150, 40, 40);
            lblDiferencia.Location = new Point(390, 13);
            lblDiferencia.Name = "lblDiferencia";
            lblDiferencia.Size = new Size(150, 25);
            lblDiferencia.TabIndex = 5;
            lblDiferencia.Text = "0.00";
            lblDiferencia.TextAlign = ContentAlignment.MiddleRight;
            btnGuardar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnGuardar.BackColor = Color.FromArgb(33, 71, 115);
            btnGuardar.FlatStyle = FlatStyle.Flat;
            btnGuardar.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            btnGuardar.ForeColor = Color.White;
            btnGuardar.Location = new Point(662, 25);
            btnGuardar.Name = "btnGuardar";
            btnGuardar.Size = new Size(140, 45);
            btnGuardar.TabIndex = 6;
            btnGuardar.Text = "Guardar asiento";
            btnGuardar.UseVisualStyleBackColor = false;
            btnGuardar.Click += btnGuardar_Click;
            btnLimpiar.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnLimpiar.FlatStyle = FlatStyle.Flat;
            btnLimpiar.Location = new Point(808, 25);
            btnLimpiar.Name = "btnLimpiar";
            btnLimpiar.Size = new Size(110, 45);
            btnLimpiar.TabIndex = 7;
            btnLimpiar.Text = "Limpiar";
            btnLimpiar.UseVisualStyleBackColor = true;
            btnLimpiar.Click += btnLimpiar_Click;
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(940, 575);
            Controls.Add(dgvDetalle);
            Controls.Add(panelInferior);
            Controls.Add(grpAgregar);
            Controls.Add(grpDatos);
            Controls.Add(panelEncabezado);
            Name = "FrmLibroDiario";
            Text = "Libro Diario";
            Load += FrmLibroDiario_Load;
            panelEncabezado.ResumeLayout(false);
            panelEncabezado.PerformLayout();
            grpDatos.ResumeLayout(false);
            grpDatos.PerformLayout();
            grpAgregar.ResumeLayout(false);
            grpAgregar.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)dgvDetalle).EndInit();
            panelInferior.ResumeLayout(false);
            panelInferior.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Panel panelEncabezado;
        private Label lblTitulo;
        private GroupBox grpDatos;
        private Label lblNumeroCap;
        private Label lblNumero;
        private Label lblFechaCap;
        private DateTimePicker dtpFecha;
        private Label lblConceptoCap;
        private TextBox txtConcepto;
        private GroupBox grpAgregar;
        private Label lblCuenta;
        private ComboBox cboCuenta;
        private Label lblConceptoLinea;
        private TextBox txtConceptoLinea;
        private Label lblDebe;
        private TextBox txtDebe;
        private Label lblHaber;
        private TextBox txtHaber;
        private Button btnAgregarLinea;
        private Button btnQuitarLinea;
        private Button btnCalcIva;
        private DataGridView dgvDetalle;
        private Panel panelInferior;
        private Label lblTotDebeCap;
        private Label lblTotDebe;
        private Label lblTotHaberCap;
        private Label lblTotHaber;
        private Label lblDifCap;
        private Label lblDiferencia;
        private Button btnGuardar;
        private Button btnLimpiar;
    }
}
